### ISSUE TITLE
<gateway>/web/ redirects to <webui>/web/ internal service address

### ISSUE THREAD

**Issue by groldan** [camptocamp/geoserver-microservices#14]
The problem is with the login form, once logged in `http://localhost:9090/j_spring_security_check` returns a 302 redirecting to `http://172.20.0.9:8080/web` (or whatever the internal service is).

**Comment by MkLHX** [comment]
Hello,
Sorry for posting in closed issue but I'm facing an issue when i login or logout with my own geoserver-cloud instance.

I've boot docker containers inside my server and configure my Caddy http server to redirect my domain to container.

But when i login i get this error:

j_spring_security_check

![image](https://user-images.githubusercontent.com/17542841/201061010-69b2708a-fb6c-4b5e-ba03-032e4f7caaf7.png)

I'm not familiar with geoserver and i don't know if this issue is related about spring, java, geoserver, geoserver-cloud...

I'm just need to configure my own instance of geoserver.

I need help or documentation to manage it.

**Comment by MkLHX** [comment]
ping https://github.com/geoserver/geoserver-cloud/issues/318
